# Generated by Django 5.1.7 on 2025-05-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy_value',
            field=models.TextField(default='Без даних'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Без даних'),
            preserve_default=False,
        ),
    ]
