# Generated by Django 5.1.7 on 2025-05-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_energy_value_product_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
